"""
This script is using python-twitter SDK (https://github.com/bear/python-twitter)
All key and secret strings can be generated by creating an app in https://apps.twitter.com/
"""

import twitter

consumer_key = '7NurZcSExcHj4wiGBYA81PVby'
consumer_secret = 'AvYxTztcpuSj7ORY7y0QKouLmZgvPax3P5IAZP6lSs5bgGKqjw'
access_token_key = '7NurZcSExcHj4wiGBYA81PVby'
access_token_secret = 'AAAAAAAAAAAAAAAAAAAAAEzGbgEAAAAAu4IiafIBYL6VDfYtPgRERte7nEo%3DvHVhaheC4us7Tsa9tNnLhEidIEV3yNkuxuRx3peyi2rtTYqof6'

api = twitter.Api(
  consumer_key=consumer_key,
  consumer_secret=consumer_secret,
  access_token_key=access_token_key,
  access_token_secret=access_token_secret
)

# Delete own tweets
owned_status = api.GetUserTimeline(count=200)
num_owned_status = 0
while(len(owned_status) > 0):
  for s in owned_status:
    api.DestroyStatus(s.id)
    print('One tweet deleted')
    num_owned_status += 1
  owned_status = api.GetUserTimeline(count=200)

print('Your ' + str(num_owned_status) + ' tweets has been deleted.')

# Delete replies
owned_replies = api.GetReplies(count=200)
num_owned_replies = 0
while(len(owned_replies) > 0):
  for s in owned_replies:
    api.DestroyStatus(s.id)
    print('One reply deleted')
    num_owned_replies += 1
  owned_replies = api.GetReplies(count=200)
  
print('Your ' + str(num_owned_replies) + ' replies has been deleted.')
